name: Annihilation
main: com.gmail.lynx7478.anni.main.AnnihilationMain
version: 1.5.5
authors: [Mr_Little_Kitty, SKAIV]
description: Annihilation minigame plugin.
commands:
  Anni:
    description: provides commands for the Annihilation game
  Team:
    description: Command related to annihilation team
  Area:
    description: Command for managing annihilation areas
  Vote:
    description: Allows players to vote for a map in annihilation
  Kit:
    description: Opens the kit menu for the player
  enderchest:
    aliases: [ec, echest, enderc]
    description: Opens the enderchest.
  changeteam:
    aliases: [ct]
    description: Changes a players team.
permissions:
  A.anni:
    description: gives permission to use the anni command
    default: op
  A.Area:
    description: gives permission to use the anni command
    default: op
  Anni.ChangeKit:
    description: allows a player to change their kit with a command
    default: op
  Anni.JoinPhase.3:
    default: false
  Anni.JoinPhase.4:
    default: false
  Anni.JoinPhase.5:
    default: false
  Anni.BypassJoin:
    default: false
  Anni.EC:
    default: false
  Anni.ChangeTeam:
    default: false
  Anni.ChatSpy:
    default: op